# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(max_length=64000)),
                ('title', models.CharField(max_length=200)),
                ('input_field', models.CharField(blank=True, max_length=200)),
                ('choices', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='adventures.Choice')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Question'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='first_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Question'),
        ),
    ]
